# Crie uma situação em que ocorra uma exceção dentro de um código.
# Utilize try/catch para realizar a captura e tratamento dessa exceção.

try :

    print(4/0)

except ZeroDivisionError as erro:

    print("Erro:", erro)

    
